language: node_js
node_js:
  - "node"
install:
  - npm i -g npm
  - npm ci
script:
  - npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run standard
  - npm run flow
deploy:
  provider: npm
  email: bret.maxime@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true